# Builds the dot cloud for the testimonials globe.
# Points are spread evenly over a sphere (Fibonacci), and only the ones on land are kept.
# Output: lib/globeDots.ts — [lon, lat, lon, lat, ...] in degrees.
#   python3 scripts/globe-dots.py 16000      (more points = denser globe)
import json, math, os, sys

here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, 'world-dots.py')).read()
exec(src[: src.index('step = ')])  # reuse the continent outlines (P, HOLES, inside)

def antarctica(lon, lat):
    if lat <= -71: return True
    coast = -67.5 - 2.5 * math.sin(math.radians(lon * 2 + 40))
    if lat <= coast: return True
    return -68 <= lon <= -56 and -71 <= lat <= -63  # the peninsula

N = int(sys.argv[1]) if len(sys.argv) > 1 else 16000
golden = math.pi * (3 - math.sqrt(5))
dots = []
for i in range(N):
    y = 1 - (i + 0.5) / N * 2
    lat = math.degrees(math.asin(y))
    lon = math.degrees((i * golden) % (2 * math.pi)) - 180
    land = antarctica(lon, lat) or (
        any(inside(lon, lat, p) for p in P.values()) and not any(inside(lon, lat, h) for h in HOLES)
    )
    if land:
        dots += [round(lon, 2), round(lat, 2)]

out = os.path.join(here, '..', 'lib', 'globeDots.ts')
with open(out, 'w') as f:
    f.write('/** Land dots for the globe (generated by scripts/globe-dots.py): [lon, lat, ...] in degrees. */\n')
    f.write('export const GLOBE_DOTS: number[] = ' + json.dumps(dots, separators=(',', ':')) + ';\n')
print(len(dots) // 2, 'land dots of', N)
